<a href="https://colab.research.google.com/github/Ayush-0918/-Pandas-lab-work/blob/main/Pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
'''
PANDAS

it is a python library which is used for data manipulation and data analysis

*it helps to load,clean,transfrom,analysis and explore data
*stand for --->"panel data system"

who created pandas -- wes Mckinney(2008)

why was pandas created ---> to handle the missing values,duplicates,cloums names,
pandas not only sloves math it will slove the real world data

*load
*clean
*manipulate(filter,sort,merge)
*to analyze the data ML

'''

'\nPANDAS \n\nit is a python library which is used for data manipulation and data analysis\n\n*it helps to load,clean,transfrom,analysis and explore data\n*stand for --->"panel data system"\n\nwho created pandas -- wes Mckinney(2008)\n\nwhy was pandas created ---> to handle the missing values,duplicates,cloums names,\npandas not only sloves math it will slove the real world data\n\n*load\n*clean\n*manipulate(filter,sort,merge)\n*to analyze the data ML\n\n'

In [ ]:
pip install pandas

Requirement already satisfied: pandas in /usr/local/lib/python3.13/dist-packages (2.2.3)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.13/dist-packages (from pandas) (2.1.3)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.13/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.13/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.13/dist-packages (from pandas) (2026.3)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.13/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
'''
how pandas works

pandas has 2 structure

1.series -- it is a one-dimensional label array/data
2.dataframe --- it is a two-dimensional label array/data

'''

'\nhow pandas works\n\npandas has 2 structure\n\n1.series -- it is a one-dimensional label array/dat\n2.dataframe --- it is a two-dimensional label array/dat\n\n'

In [ ]:
'''
series

*it is 1d labeled array
*it is simple coloumn data with index
*it stores number,string,boolean -- mixed datatype

series=data+index

'''

'\nseries \n\n*it is 1d labeled array\n*it is simple coloumn data with index\n*it stores number,string,boolean -- mixed datatype\n\nseries=data+index\n\n'

In [ ]:
#creating series
s=pd.Series([10,20,30,40,50,60,70,80,90,'a'])
print(s)
print(type(s))

0    10
1    20
2    30
3    40
4    50
5    60
6    70
7    80
8    90
9     a
dtype: object
<class 'pandas.core.series.Series'>

In [ ]:
#creating series using dict
#key ---> index
#value ---> data
s1=pd.Series({'a':101,'b':'hello','c':'pandas'})
print(s1)
print(type(s1))

a       101
b     hello
c    pandas
dtype: object
<class 'pandas.core.series.Series'>

In [ ]:
'''
dataframe

*a dataframe is a 2d labeled,tabular data structure in python
*a table with rows and coloumns
*dataframe == multiple series aligned with index

'''

'\ndataframe \n\n*a dataframe is a 2d labeled,tabular data structure in python\n*a table with rows and coloumns\n*dataframe == multiple series aligned with index \n\n'

In [ ]:
#creating dataframe using dictionary
d1={'a':['raju','amit','smiran'],'b':[101,102,103],'c':['red','yellow','green']}
print(d1)

{'a': ['raju', 'amit', 'smiran'], 'b': [101, 102, 103], 'c': ['red', 'yellow', 'green']}

In [ ]:
df1=pd.DataFrame(d1)
print(df1)

        a    b       c
0    raju  101     red
1    amit  102  yellow
2  smiran  103   green

In [ ]:
#creating df using list
data=[['rahul',21,86],
      ['priya',22,90],
      ['amit',20,78]]
df=pd.DataFrame(data,columns=['name','age','marks'])
print(df)

    name  age  marks
0  rahul   21     86
1  priya   22     90
2   amit   20     78

In [ ]:
#reading the files

#df=pd.read_csv("path") #reading csv file
#df=pd.read_excel("path") #reading excel file

In [ ]:
#basis dataframe attributes

d1={'a':['raju','amit','smiran'],'b':[101,102,103],'c':['red','yellow','green']}
df2=pd.DataFrame(d1)
print(df2)

        a    b       c
0    raju  101     red
1    amit  102  yellow
2  smiran  103   green

In [ ]:
#shape -- number of rows and columns
print(df2.shape)

(3, 3)

In [ ]:
#size -- total numbers of elements
print(df2.size)

9

In [ ]:
#columns --- display all the columsn present in dataframe
print(df2.columns)

Index(['a', 'b', 'c'], dtype='object')

In [ ]:
#dtype -- datatype of each columns
print(df2.dtypes)

a    object
b     int64
c    object
dtype: object

In [ ]:
#viewing the data
print(df2)

        a    b       c
0    raju  101     red
1    amit  102  yellow
2  smiran  103   green

In [ ]:
#head() --- give me only the top most row
print(df2.head()) #default value is 5(first five)

        a    b       c
0    raju  101     red
1    amit  102  yellow
2  smiran  103   green

In [ ]:
#tail() -- it will give me bottom rows(default 5)
print(df2.tail(1))

        a    b      c
2  smiran  103  green

In [ ]:
#info() --- information of data ---> columns,null values count,datatypes
print(df2.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   a       3 non-null      object
 1   b       3 non-null      int64
 2   c       3 non-null      object
dtypes: int64(1), object(2)
memory usage: 204.0+ bytes
None

In [ ]:
#describe() -- statistical summary of data
#it will work only on numberic columns
print(df2.describe())

           b
count    3.0
mean   102.0
std      1.0
min    101.0
25%    101.5
50%    102.0
75%    102.5
max    103.0

In [ ]:
#sample --- >it will give random rows
print(df.sample(2))

    name  age  marks
2   amit   20     78
0  rahul   21     86

In [ ]:
#accessing elements from dataframe

print(df2)

        a    b       c
0    raju  101     red
1    amit  102  yellow
2  smiran  103   green

In [ ]:
#single columns
print(df2['b'])

0    101
1    102
2    103
Name: b, dtype: int64

In [ ]:
#multiple elemenst
print(df2[['a','c']])

        a       c
0    raju     red
1    amit  yellow
2  smiran   green

In [ ]:
df1=pd.DataFrame({'name':['riya','siya','abhi','mayank'],'age':[29,19,18,25],'gender':['f','f','m','m']})

In [ ]:
print(df1)
print(df1.shape)

     name  age gender
0    riya   29      f
1    siya   19      f
2    abhi   18      m
3  mayank   25      m
(4, 3)

In [ ]:
'''
2 important method for accessing values

1.loc -- this method uses label based access
2.iloc -- this methpod uses position based (i-- integer)
'''

'\n2 important method for accessing values\n\n1.loc -- this method uses label based access\n2.iloc -- this methpod uses position based (i-- integer)\n'

In [ ]:
#loc --- where we will use label to access
print(df1.loc[3])

name      mayank
age           25
gender         m
Name: 3, dtype: object

In [ ]:
print(df1.loc[1:2])

   name  age gender
1  siya   19      f
2  abhi   18      m

In [ ]:
print(df1.loc[1:2,['name','gender']])

   name gender
1  siya      f
2  abhi      m

In [ ]:
#iloc --- > position based
print(df1.iloc[0:2]) #-- it is saying start from 0 and go till 2-1

   name  age gender
0  riya   29      f
1  siya   19      f

In [ ]:
print(df1.iloc[0:2,0:4])

   name  age gender
0  riya   29      f
1  siya   19      f

In [ ]:
print(df1)

     name  age gender
0    riya   29      f
1    siya   19      f
2    abhi   18      m
3  mayank   25      m

In [ ]:
#conditional filtering
print(df1)

     name  age gender
0    riya   29      f
1    siya   19      f
2    abhi   18      m
3  mayank   25      m

In [ ]:
print(df1[df1['gender']=='f'])

   name  age gender
0  riya   29      f
1  siya   19      f

In [ ]:
print(df1['gender']=='f')

0     True
1     True
2    False
3    False
Name: gender, dtype: bool

In [ ]:
#multiple condition
df1[(df1['age']>20) & (df1['gender']=='f') ]

   name  age gender
0  riya   29      f

In [ ]:
#dataframe manipulation(drop,rename)
#1.remove columns
print(df1.drop('age',axis=1)) #axis=1 --> is to sepecify column(0 is for row)

     name gender
0    riya      f
1    siya      f
2    abhi      m
3  mayank      m

In [ ]:
print(df1)

     name  age gender
0    riya   29      f
1    siya   19      f
2    abhi   18      m
3  mayank   25      m

In [ ]:
df3=pd.DataFrame({'name':['riya','siya','abhi','mayank'],'age':[29,19,18,25],'gender':['f','f','m','m']})

In [ ]:
print(df3)

     name  age gender
0    riya   29      f
1    siya   19      f
2    abhi   18      m
3  mayank   25      m

In [ ]:
print(df3.drop('age',axis=1,inplace=True))

None

In [ ]:
#inplace=True ---> for prement change

In [ ]:
print(df3)

     name gender
0    riya      f
1    siya      f
2    abhi      m
3  mayank      m

In [ ]:
#rename columns
#syntax ---> df.rename(columns={oldname:new_name})
print(df3.rename(columns={'name':'first_name'}))

  first_name gender
0       riya      f
1       siya      f
2       abhi      m
3     mayank      m

In [ ]:
print(df3)

     name gender
0    riya      f
1    siya      f
2    abhi      m
3  mayank      m

In [ ]:
#add column --> df['cal_name']=[values]
df3['experience']=[1,2,2,3]

In [ ]:
print(df3)

     name gender  experience
0    riya      f           1
1    siya      f           2
2    abhi      m           2
3  mayank      m           3

In [ ]:
#sorting
df3.sort_values('experience',ascending=True)

     name gender  experience
0    riya      f           1
1    siya      f           2
2    abhi      m           2
3  mayank      m           3

In [ ]:
print(df3.sort_index())

     name gender  experience
0    riya      f           1
1    siya      f           2
2    abhi      m           2
3  mayank      m           3

In [ ]:
#concatenation --- combaning the 2 or more dataframe
d1=pd.DataFrame({'id':[1,2],'name':['a','b']})
d2=pd.DataFrame({'age':[29,30],'grade':['c','d']})

print(pd.concat([d1,d2],axis=1))

   id name  age grade
0   1    a   29     c
1   2    b   30     d

In [ ]:
print(df3)
df3.loc[4]=['advik','m',5]
print(df3)

     name gender  experience
0    riya      f           1
1    siya      f           2
2    abhi      m           2
3  mayank      m           3
4   advik      m           5
     name gender  experience
0    riya      f           1
1    siya      f           2
2    abhi      m           2
3  mayank      m           3
4   advik      m           5

In [ ]:
'''
1.create a pandas series with 10 integer value,perfrom the following operations

*print first 5 eleemts
*print last 3 elements
*update the last element in the series with 100
*delet the first element from series

@9:20
'''

'\n1.create a pandas series with 10 integer value,perfrom the following operations\n\n*print first 5 eleemts\n*print last 3 elements\n*update the last element in the series with 100\n*delet the first element from series\n\n@9:20\n'

In [ ]:
import pandas as pd

In [ ]:
s1=pd.Series([30,40,50,60,1,2,3,4,5,6])
print(s1)

0    30
1    40
2    50
3    60
4     1
5     2
6     3
7     4
8     5
9     6
dtype: int64

In [ ]:
print(s1.head())

0    30
1    40
2    50
3    60
4     1
dtype: int64

In [ ]:
print(s1.tail(3))

7    4
8    5
9    6
dtype: int64

In [ ]:
s1[9]=100

In [ ]:
print(s1)

0     30
1     40
2     50
3     60
4      1
5      2
6      3
7      4
8      5
9    100
dtype: int64

In [ ]:
s1.drop(0)

1     40
2     50
3     60
4      1
5      2
6      3
7      4
8      5
9    100
dtype: int64

In [ ]:
'''
2.create a dataframe with columns --> name,age and city ,perform the following task

*print first 2 element and last 2 eleemnet
*get the information about dataframedf
*select any one column
*filter the rows based on condition age>20
*drop teh column city
*sort the dataframe by age column in descending order

@9:35

'''

'\n2.create a dataframe with columns --> name,age and city ,perform the following task\n\n*print first 2 element and last 2 eleemnet \n*get the information about dataframe\n*select any one column\n*filter the rows based on condition age>20\n*drop teh column city\n*sort the dataframe by age column in descending order\n\n@9:35\n\n'

In [ ]:
data=pd.DataFrame({'name':['a','b','c','d'],'age':[21,27,24,19],'city':['delhi','pune','bangalore','delhi']})

In [ ]:
print(data)

  name  age       city
0    a   21      delhi
1    b   27       pune
2    c   24  bangalore
3    d   19      delhi

In [ ]:
print(data.head(2))

  name  age   city
0    a   21  delhi
1    b   27   pune

In [ ]:
print(data.tail(2))

  name  age       city
2    c   24  bangalore
3    d   19      delhi

In [ ]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   name    4 non-null      object
 1   age     4 non-null      int64
 2   city    4 non-null      object
dtypes: int64(1), object(2)
memory usage: 228.0+ bytes

In [ ]:
print(data['name'])

0    a
1    b
2    c
3    d
Name: name, dtype: object

In [ ]:
data[data['age']>20]

  name  age       city
0    a   21      delhi
1    b   27       pune
2    c   24  bangalore

In [ ]:
data.drop('city',axis=1,inplace=True)

In [ ]:
print(data)

  name  age
0    a   21
1    b   27
2    c   24
3    d   19

In [ ]:
data.sort_values('age',ascending=False)

  name  age
1    b   27
2    c   24
0    a   21
3    d   19

In [ ]:
'''
3.
a.create two series and perform series concatination
b.create two dataframe and perform dataframe concatination(row wise)

@9:47
'''

'\n3.\na.create two series and perform series concatination\nb.create two dataframe and perform dataframe concatination(row wise)\n\n@9:47\n'

In [ ]:
s1=pd.Series([1,2,3,4])
s2=pd.Series([30,40,50,60])
pd.concat([s1,s2])

0     1
1     2
2     3
3     4
0    30
1    40
2    50
3    60
dtype: int64

In [ ]:
df1=pd.DataFrame({'id':[1,2,3,4],'gender':['m','f','m','m']})
df2=pd.DataFrame({'name':['a','b','c','d'],'garde':['a','b','a+','o']})
pd.concat([df1,df2],axis=0)

    id gender name garde
0  1.0      m  NaN   NaN
1  2.0      f  NaN   NaN
2  3.0      m  NaN   NaN
3  4.0      m  NaN   NaN
0  NaN    NaN    a     a
1  NaN    NaN    b     b
2  NaN    NaN    c    a+
3  NaN    NaN    d     o

In [ ]:
'''
flitering and multiple condition
4.create a dataframe containg name, age, city and marks,perfom the following task

*displasy student whose marks are grater than 70
*display student whose age is less than 20
*fliter the student whose marks are greater than 60 and age is less than 20
*select only name abd marks columns
*sort dataframe by marks in descending order

@10:01
'''

'\nflitering and multiple condition\n4.create a dataframe containg name, age, city and marks,perfom the following task\n\n*displasy student whose marks are grater than 70\n*display student whose age is less than 20\n*fliter the student whose marks are greater than 60 and age is less than 20\n*select only name abd marks columns\n*sort dataframe by marks in descending order\n\n@10:01\n'

In [ ]:
data={'name':['aman','riya','kunal','sneha','vikas'],
      'age':[19,21,18,20,17],
      'city':['delhi','mumbai','pune','delhi','banaglore'],
      'marks':[75,65,88,55,92]}
df=pd.DataFrame(data)

In [ ]:
print(df)

    name  age       city  marks
0   aman   19      delhi     75
1   riya   21     mumbai     65
2  kunal   18       pune     88
3  sneha   20      delhi     55
4  vikas   17  banaglore     92

In [ ]:
print(df[df['marks']>70])

    name  age       city  marks
0   aman   19      delhi     75
2  kunal   18       pune     88
4  vikas   17  banaglore     92

In [ ]:
print(df[df['age']<20])

    name  age       city  marks
0   aman   19      delhi     75
2  kunal   18       pune     88
4  vikas   17  banaglore     92

In [ ]:
print(df[(df['marks']>60) & (df['age']<20)])

    name  age       city  marks
0   aman   19      delhi     75
2  kunal   18       pune     88
4  vikas   17  banaglore     92

In [ ]:
print(df[['name','marks']])

    name  marks
0   aman     75
1   riya     65
2  kunal     88
3  sneha     55
4  vikas     92

In [ ]:
df.sort_values('marks',ascending=False)

    name  age       city  marks
4  vikas   17  banaglore     92
2  kunal   18       pune     88
0   aman   19      delhi     75
1   riya   21     mumbai     65
3  sneha   20      delhi     55

In [ ]:
'''
5.create a dataframe with column name,marks1,marks2,marks3 perfrom the following task

*add new column total containg total marks
*add new column average containg the average marks
*add a column result where student with avg>=40 are "pass" orelse "fail"
*display stuents who have passed
*print teh final dataframe

@10:17
'''

'\n5.create a dataframe with column name,marks1,marks2,marks3 perfrom the following task\n\n*add new column total containg total marks\n*add new column average containg the average marks\n*add a column result where student with avg>=40 are "pass" orelse "fail"\n*display stuents who have passed\n*print teh final dataframe \n\n@10:17\n'

In [ ]:
data={'name':['amit','riya','karan','neha','vikas'],
      'marks1':[70,45,30,80,55],
      'marks2':[65,50,35,75,60],
      'marks3':[75,40,25,85,50]}
df=pd.DataFrame(data)
print(df)

    name  marks1  marks2  marks3
0   amit      70      65      75
1   riya      45      50      40
2  karan      30      35      25
3   neha      80      75      85
4  vikas      55      60      50

In [ ]:
df['total']=df['marks1']+df['marks2']+df['marks3']

In [ ]:
df['avg']=df['total']/3

In [ ]:
df['result']=df['avg'].apply(lambda x:'pass' if x>=40 else "fail")

In [ ]:
df[df['result']=='pass']

    name  marks1  marks2  marks3  total   avg result
0   amit      70      65      75    210  70.0   pass
1   riya      45      50      40    135  45.0   pass
3   neha      80      75      85    240  80.0   pass
4  vikas      55      60      50    165  55.0   pass

In [ ]:
print(df)

    name  marks1  marks2  marks3  total   avg result
0   amit      70      65      75    210  70.0   pass
1   riya      45      50      40    135  45.0   pass
2  karan      30      35      25     90  30.0   fail
3   neha      80      75      85    240  80.0   pass
4  vikas      55      60      50    165  55.0   pass

In [ ]:
'''
EDA ---> exploratory data analysis

it is process of understanding data before doing the ,achine learing

1.load data
2.understanding the structure
3.chechking datatype
4.finding missing values
5.filling missing values
6.finding duplicates values
7.handling dupllicate values
8.looking for outliers


'''

In [ ]:
from google.colab import files
uploaded=files.upload()

Saving new_insurance_data (1).csv to new_insurance_data (1).csv

In [ ]:
import pandas as pd
df =pd.read_csv('new_insurance_data (1).csv')

In [ ]:
df.head()

,age,sex,bmi,children,smoker,Claim_Amount,past_consultations,num_of_steps,Hospital_expenditure,NUmber_of_past_hospitalizations,Anual_Salary,region,charges
0,18.0,male,23.21,0.0,no,29087.54313,17.0,715428.0,4720920.992,0.0,55784970.05,southeast,1121.8739
1,18.0,male,30.14,0.0,no,39053.67437,7.0,699157.0,4329831.676,0.0,13700885.19,southeast,1131.5066
2,18.0,male,33.33,0.0,no,39023.62759,19.0,702341.0,6884860.774,0.0,73523107.27,southeast,1135.9407
3,18.0,male,33.66,0.0,no,28185.39332,11.0,700250.0,4274773.550,0.0,75819679.60,southeast,1136.3994
4,18.0,male,34.10,0.0,no,14697.85941,16.0,711584.0,3787293.921,0.0,23012320.01,southeast,1137.0110

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1338 entries, 0 to 1337
Data columns (total 13 columns):
 #   Column                           Non-Null Count  Dtype
---  ------                           --------------  -----
 0   age                              1329 non-null   float64
 1   sex                              1338 non-null   object
 2   bmi                              1335 non-null   float64
 3   children                         1333 non-null   float64
 4   smoker                           1338 non-null   object
 5   Claim_Amount                     1324 non-null   float64
 6   past_consultations               1332 non-null   float64
 7   num_of_steps                     1335 non-null   float64
 8   Hospital_expenditure             1334 non-null   float64
 9   NUmber_of_past_hospitalizations  1336 non-null   float64
 10  Anual_Salary                     1332 non-null   float64
 11  region                           1338 non-null   object
 12  charges                          1338 non-null   float64
dtypes: float64(10), object(3)
memory usage: 136.0+ KB

In [ ]:
df.tail()

,age,sex,bmi,children,smoker,Claim_Amount,past_consultations,num_of_steps,Hospital_expenditure,NUmber_of_past_hospitalizations,Anual_Salary,region,charges
1333,33.0,female,35.530,0.0,yes,63142.25346,32.0,1091267.0,170380500.5,2.0,3.101107e+09,northwest,55135.40209
1334,31.0,female,38.095,1.0,yes,43419.95227,31.0,1107872.0,201515184.8,2.0,3.484216e+09,northeast,58571.07448
1335,52.0,male,34.485,3.0,yes,52458.92353,25.0,1092005.0,223644981.3,2.0,3.640807e+09,northwest,60021.39897
1336,45.0,male,30.360,0.0,yes,69927.51664,34.0,1106821.0,252892382.6,3.0,4.006359e+09,southeast,62592.87309
1337,54.0,female,47.410,0.0,yes,63982.80926,31.0,1100328.0,261631699.3,3.0,4.117197e+09,southeast,63770.42801

In [ ]:
df.describe()

,age,bmi,children,Claim_Amount,past_consultations,num_of_steps,Hospital_expenditure,NUmber_of_past_hospitalizations,Anual_Salary,charges
count,1329.000000,1335.000000,1333.000000,1324.000000,1332.000000,1.335000e+03,1.334000e+03,1336.000000,1.332000e+03,1338.000000
mean,39.310008,30.665112,1.090773,33361.327180,15.216216,9.100047e+05,1.584179e+07,1.060629,3.696849e+08,13270.422265
std,14.034818,6.101690,1.201856,15617.288337,7.467723,9.188612e+04,2.669305e+07,0.533583,5.668843e+08,12110.011237
min,18.000000,15.960000,0.000000,1920.136268,1.000000,6.954300e+05,2.945253e+04,0.000000,2.747072e+06,1121.873900
25%,27.000000,26.302500,0.000000,20768.860390,9.000000,8.471995e+05,4.077633e+06,1.000000,7.701932e+07,4740.287150
50%,39.000000,30.400000,1.000000,33700.310675,15.000000,9.143000e+05,7.490337e+06,1.000000,1.419361e+08,9382.033000
75%,51.000000,34.687500,2.000000,45052.331957,20.000000,9.716840e+05,1.084082e+07,1.000000,3.243499e+08,16639.912515
max,64.000000,53.130000,5.000000,77277.988480,40.000000,1.107872e+06,2.616317e+08,3.000000,4.117197e+09,63770.428010

In [ ]:
df['age']

0       18.0
1       18.0
2       18.0
3       18.0
4       18.0
        ...
1333    33.0
1334    31.0
1335    52.0
1336    45.0
1337    54.0
Name: age, Length: 1338, dtype: float64

In [ ]:
df.columns

Index(['age', 'sex', 'bmi', 'children', 'smoker', 'Claim_Amount',
       'past_consultations', 'num_of_steps', 'Hospital_expenditure',
       'NUmber_of_past_hospitalizations', 'Anual_Salary', 'region', 'charges'],
      dtype='object')

In [ ]:
df.iloc[1]

age                                       18.0
sex                                       male
bmi                                      30.14
children                                   0.0
smoker                                      no
Claim_Amount                       39053.67437
past_consultations                         7.0
num_of_steps                          699157.0
Hospital_expenditure               4329831.676
NUmber_of_past_hospitalizations            0.0
Anual_Salary                       13700885.19
region                               southeast
charges                              1131.5066
Name: 1, dtype: object

In [ ]:
df.iloc[[0,1,2]]

,age,sex,bmi,children,smoker,Claim_Amount,past_consultations,num_of_steps,Hospital_expenditure,NUmber_of_past_hospitalizations,Anual_Salary,region,charges
0,18.0,male,23.21,0.0,no,29087.54313,17.0,715428.0,4720920.992,0.0,55784970.05,southeast,1121.8739
1,18.0,male,30.14,0.0,no,39053.67437,7.0,699157.0,4329831.676,0.0,13700885.19,southeast,1131.5066
2,18.0,male,33.33,0.0,no,39023.62759,19.0,702341.0,6884860.774,0.0,73523107.27,southeast,1135.9407

In [ ]:
df.iloc[0:1]

,age,sex,bmi,children,smoker,Claim_Amount,past_consultations,num_of_steps,Hospital_expenditure,NUmber_of_past_hospitalizations,Anual_Salary,region,charges
0,18.0,male,23.21,0.0,no,29087.54313,17.0,715428.0,4720920.992,0.0,55784970.05,southeast,1121.8739

In [ ]:
print(df.iloc[0,2])

23.21

In [ ]:
print(df.loc[0,'age'])

18.0

In [ ]:
print(df['age']>50)

0       False
1       False
2       False
3       False
4       False
        ...
1333    False
1334    False
1335     True
1336    False
1337     True
Name: age, Length: 1338, dtype: bool

In [ ]:
df[(df['age']>50) & (df['sex']=='male') & (df['smoker'] == 'no')]

,age,sex,bmi,children,smoker,Claim_Amount,past_consultations,num_of_steps,Hospital_expenditure,NUmber_of_past_hospitalizations,Anual_Salary,region,charges
631,51.0,male,25.400,0.0,no,40402.92285,6.0,898991.0,4.909391e+06,1.0,1.419532e+08,southwest,8782.46900
632,51.0,male,37.000,0.0,no,14412.66913,9.0,914995.0,3.300942e+06,1.0,1.225365e+08,southwest,8798.59300
652,52.0,male,34.100,0.0,no,14289.59451,6.0,901114.0,5.854792e+06,1.0,9.947616e+07,southeast,9140.95100
653,52.0,male,36.700,0.0,no,35832.46753,9.0,910353.0,9.508487e+06,1.0,1.208236e+08,southwest,9144.56500
654,51.0,male,31.635,0.0,no,42322.35008,16.0,914300.0,3.888710e+06,1.0,1.012005e+08,northwest,9174.13565
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1158,53.0,male,31.350,0.0,no,41341.65752,14.0,1023422.0,2.619570e+07,2.0,8.399665e+08,southeast,27346.04207
1163,61.0,male,36.100,3.0,no,51434.29984,21.0,1031270.0,3.067218e+07,2.0,8.173708e+08,southwest,27941.28758
1176,55.0,male,37.715,3.0,no,60383.15233,26.0,1033197.0,3.384885e+07,2.0,9.292044e+08,northwest,30063.58055
1177,64.0,male,24.700,1.0,no,21006.56144,31.0,1044427.0,3.296596e+07,2.0,9.777793e+08,northwest,30166.61817
1179,60.0,male,28.595,0.0,no,58382.02948,18.0,1032051.0,3.471964e+07,2.0,9.916299e+08,northeast,30259.99556