<a href="https://colab.research.google.com/github/Ayush-0918/-Pandas-lab-work/blob/main/Pandas_learning.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np
import pandas as pd

In [3]:
dict = {
    "name":["Aayu","Varshu","Aman","Vishal"],
    "marks":[92,96,78,67],
    "roll no":[1,2,3,4]
}

In [4]:
df = pd.DataFrame(dict)

In [5]:
df

     name  marks  roll no
0    Aayu     92        1
1  Varshu     96        2
2    Aman     78        3
3  Vishal     67        4

In [6]:
df.to_csv('friends.csv')

In [7]:
df.to_excel('friends1.xlsx')

In [8]:
df.head(2)

     name  marks  roll no
0    Aayu     92        1
1  Varshu     96        2

In [9]:
df.tail(2)

     name  marks  roll no
2    Aman     78        3
3  Vishal     67        4

In [10]:
df.describe()

           marks   roll no
count   4.000000  4.000000
mean   83.250000  2.500000
std    13.301002  1.290994
min    67.000000  1.000000
25%    75.250000  1.750000
50%    85.000000  2.500000
75%    93.000000  3.250000
max    96.000000  4.000000

In [11]:
friends_marks = pd.read_csv('friends.csv')

In [12]:
friends_marks

   Unnamed: 0    name  marks  roll no
0           0    Aayu     92        1
1           1  Varshu     96        2
2           2    Aman     78        3
3           3  Vishal     67        4

In [13]:
friends_marks['marks']

0    92
1    96
2    78
3    67
Name: marks, dtype: int64

In [14]:
friends_marks['marks'][1]=93

/tmp/ipykernel_3510/1264105317.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  friends_marks['marks'][1]=93

In [15]:
friends_marks

   Unnamed: 0    name  marks  roll no
0           0    Aayu     92        1
1           1  Varshu     93        2
2           2    Aman     78        3
3           3  Vishal     67        4

In [16]:
friends_marks.to_csv('friends.csv')

In [17]:
ser = pd.Series(np.random.rand(10))

In [18]:
ser

0    0.585363
1    0.562465
2    0.671644
3    0.488674
4    0.123982
5    0.953074
6    0.885890
7    0.913882
8    0.848734
9    0.668847
dtype: float64

In [19]:
type(ser)

pandas.core.series.Series

In [20]:
newdf = pd.DataFrame(np.random.rand(34,5),index=np.arange(34))

In [21]:
newdf

           0         1         2         3         4
0   0.959886  0.511836  0.599295  0.403346  0.797335
1   0.130536  0.801234  0.585316  0.891765  0.559614
2   0.094989  0.801981  0.959394  0.626865  0.931248
3   0.679199  0.299262  0.944816  0.182108  0.926390
4   0.953423  0.960116  0.776280  0.952343  0.569990
5   0.349025  0.831474  0.693995  0.349263  0.956159
6   0.744081  0.270258  0.535528  0.261188  0.288204
7   0.612529  0.682731  0.471572  0.886344  0.235052
8   0.947983  0.387455  0.367191  0.662090  0.824582
9   0.833467  0.425049  0.651411  0.389147  0.741462
10  0.228807  0.124590  0.072217  0.470681  0.267328
11  0.868053  0.161427  0.791005  0.174471  0.683739
12  0.352525  0.231497  0.046574  0.153763  0.737501
13  0.271811  0.723660  0.493896  0.853978  0.059526
14  0.814683  0.376099  0.409639  0.092887  0.263281
15  0.139665  0.161190  0.449411  0.553088  0.264471
16  0.637234  0.243304  0.324089  0.024889  0.601560
17  0.714045  0.810001  0.563446  0.488816  0.822886
18  0.880156  0.320947  0.785918  0.708427  0.943367
19  0.843172  0.781721  0.265594  0.907294  0.626779
20  0.881309  0.216442  0.348141  0.622088  0.195634
21  0.871533  0.099070  0.843933  0.303112  0.926284
22  0.007057  0.503665  0.532264  0.011154  0.470287
23  0.396298  0.901180  0.545078  0.876978  0.638750
24  0.267223  0.395059  0.541185  0.882138  0.963903
25  0.324638  0.179365  0.940827  0.472601  0.786070
26  0.535643  0.480054  0.960936  0.753616  0.910707
27  0.665098  0.112418  0.532015  0.154250  0.903153
28  0.625312  0.164051  0.301665  0.120454  0.926100
29  0.330286  0.842792  0.547838  0.979716  0.099378
30  0.939924  0.970715  0.501016  0.386752  0.155596
31  0.208456  0.866507  0.026183  0.010153  0.040010
32  0.518575  0.867627  0.333345  0.722337  0.782644
33  0.490020  0.992343  0.715629  0.174819  0.199165

In [22]:
type(newdf)
newdf.head()

          0         1         2         3         4
0  0.959886  0.511836  0.599295  0.403346  0.797335
1  0.130536  0.801234  0.585316  0.891765  0.559614
2  0.094989  0.801981  0.959394  0.626865  0.931248
3  0.679199  0.299262  0.944816  0.182108  0.926390
4  0.953423  0.960116  0.776280  0.952343  0.569990

In [23]:
newdf.dtypes

0    float64
1    float64
2    float64
3    float64
4    float64
dtype: object

In [24]:
newdf[0][0] = "aayu"

/tmp/ipykernel_3510/1013117637.py:1: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  newdf[0][0] = "aayu"
/tmp/ipykernel_3510/1013117637.py:1: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value 'aayu' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  newdf[0][0] = "aayu"

In [25]:
newdf.dtypes

0     object
1    float64
2    float64
3    float64
4    float64
dtype: object

In [26]:
newdf.head()

          0         1         2         3         4
0      aayu  0.511836  0.599295  0.403346  0.797335
1  0.130536  0.801234  0.585316  0.891765  0.559614
2  0.094989  0.801981  0.959394  0.626865  0.931248
3  0.679199  0.299262  0.944816  0.182108  0.926390
4  0.953423  0.960116  0.776280  0.952343  0.569990

In [32]:
newdf.drop([1,5],axis=0)

           0         1         2         3         4
0   0.939073  0.694329  0.235491  0.998767  0.209865
2   0.213207  0.155867  0.181690  0.108672  0.704496
3   0.475311  0.116881  0.414554  0.496279  0.739244
4   0.766961  0.727010  0.408157  0.488876  0.953988
6   0.198667  0.126271  0.816297  0.280097  0.232415
7   0.733566  0.496204  0.865002  0.720784  0.395159
8   0.166537  0.589358  0.062945  0.990869  0.375793
9   0.120912  0.132913  0.756018  0.902764  0.234456
10  0.204683  0.386244  0.434552  0.275064  0.440463
11  0.010836  0.930465  0.729309  0.537067  0.641289
12  0.868909  0.417315  0.525030  0.202146  0.442074
13  0.495785  0.213845  0.636308  0.905199  0.850520
14  0.817539  0.780799  0.485089  0.552300  0.917139
15  0.505497  0.609265  0.537341  0.938665  0.594529
16  0.235798  0.797182  0.992493  0.979790  0.877888
17  0.326946  0.586031  0.489495  0.270462  0.940673
18  0.674898  0.530052  0.460547  0.881077  0.621811
19  0.188505  0.271027  0.083033  0.906150  0.070012
20  0.947308  0.440723  0.362545  0.590955  0.080748
21  0.696808  0.571051  0.160104  0.552603  0.617557
22  0.887541  0.402348  0.636019  0.948385  0.966669
23  0.836618  0.397321  0.020446  0.165099  0.019527
24  0.936129  0.258706  0.980920  0.750937  0.777780
25  0.765255  0.196671  0.117966  0.931629  0.747012
26  0.547868  0.028769  0.576159  0.894722  0.019479
27  0.791172  0.370898  0.450773  0.849026  0.282351
28  0.860817  0.254183  0.519276  0.515760  0.266051
29  0.621782  0.875806  0.783445  0.656752  0.760084
30  0.849002  0.200121  0.813363  0.053751  0.036415
31  0.608243  0.259314  0.115530  0.244495  0.116281
32  0.976921  0.902328  0.581073  0.080335  0.583380
33  0.976625  0.498177  0.630824  0.691130  0.750496

In [34]:
newdf.head(4)

          0         1         2         3         4
0  0.939073  0.694329  0.235491  0.998767  0.209865
1  0.216880  0.797940  0.419027  0.407929  0.462918
2  0.213207  0.155867  0.181690  0.108672  0.704496
3  0.475311  0.116881  0.414554  0.496279  0.739244

In [39]:
newdf[0] = None

In [40]:
newdf

       0         1         2         3         4     0
0   None  0.694329  0.235491  0.998767  0.209865  None
1   None  0.797940  0.419027  0.407929  0.462918  None
2   None  0.155867  0.181690  0.108672  0.704496  None
3   None  0.116881  0.414554  0.496279  0.739244  None
4   None  0.727010  0.408157  0.488876  0.953988  None
5   None  0.945395  0.588121  0.216811  0.016850  None
6   None  0.126271  0.816297  0.280097  0.232415  None
7   None  0.496204  0.865002  0.720784  0.395159  None
8   None  0.589358  0.062945  0.990869  0.375793  None
9   None  0.132913  0.756018  0.902764  0.234456  None
10  None  0.386244  0.434552  0.275064  0.440463  None
11  None  0.930465  0.729309  0.537067  0.641289  None
12  None  0.417315  0.525030  0.202146  0.442074  None
13  None  0.213845  0.636308  0.905199  0.850520  None
14  None  0.780799  0.485089  0.552300  0.917139  None
15  None  0.609265  0.537341  0.938665  0.594529  None
16  None  0.797182  0.992493  0.979790  0.877888  None
17  None  0.586031  0.489495  0.270462  0.940673  None
18  None  0.530052  0.460547  0.881077  0.621811  None
19  None  0.271027  0.083033  0.906150  0.070012  None
20  None  0.440723  0.362545  0.590955  0.080748  None
21  None  0.571051  0.160104  0.552603  0.617557  None
22  None  0.402348  0.636019  0.948385  0.966669  None
23  None  0.397321  0.020446  0.165099  0.019527  None
24  None  0.258706  0.980920  0.750937  0.777780  None
25  None  0.196671  0.117966  0.931629  0.747012  None
26  None  0.028769  0.576159  0.894722  0.019479  None
27  None  0.370898  0.450773  0.849026  0.282351  None
28  None  0.254183  0.519276  0.515760  0.266051  None
29  None  0.875806  0.783445  0.656752  0.760084  None
30  None  0.200121  0.813363  0.053751  0.036415  None
31  None  0.259314  0.115530  0.244495  0.116281  None
32  None  0.902328  0.581073  0.080335  0.583380  None
33  None  0.498177  0.630824  0.691130  0.750496  None

In [44]:
newdf.loc[:,[0]] = 10

In [45]:
newdf

     0         1         2         3         4     0
0   10  0.694329  0.235491  0.998767  0.209865  None
1   10  0.797940  0.419027  0.407929  0.462918  None
2   10  0.155867  0.181690  0.108672  0.704496  None
3   10  0.116881  0.414554  0.496279  0.739244  None
4   10  0.727010  0.408157  0.488876  0.953988  None
5   10  0.945395  0.588121  0.216811  0.016850  None
6   10  0.126271  0.816297  0.280097  0.232415  None
7   10  0.496204  0.865002  0.720784  0.395159  None
8   10  0.589358  0.062945  0.990869  0.375793  None
9   10  0.132913  0.756018  0.902764  0.234456  None
10  10  0.386244  0.434552  0.275064  0.440463  None
11  10  0.930465  0.729309  0.537067  0.641289  None
12  10  0.417315  0.525030  0.202146  0.442074  None
13  10  0.213845  0.636308  0.905199  0.850520  None
14  10  0.780799  0.485089  0.552300  0.917139  None
15  10  0.609265  0.537341  0.938665  0.594529  None
16  10  0.797182  0.992493  0.979790  0.877888  None
17  10  0.586031  0.489495  0.270462  0.940673  None
18  10  0.530052  0.460547  0.881077  0.621811  None
19  10  0.271027  0.083033  0.906150  0.070012  None
20  10  0.440723  0.362545  0.590955  0.080748  None
21  10  0.571051  0.160104  0.552603  0.617557  None
22  10  0.402348  0.636019  0.948385  0.966669  None
23  10  0.397321  0.020446  0.165099  0.019527  None
24  10  0.258706  0.980920  0.750937  0.777780  None
25  10  0.196671  0.117966  0.931629  0.747012  None
26  10  0.028769  0.576159  0.894722  0.019479  None
27  10  0.370898  0.450773  0.849026  0.282351  None
28  10  0.254183  0.519276  0.515760  0.266051  None
29  10  0.875806  0.783445  0.656752  0.760084  None
30  10  0.200121  0.813363  0.053751  0.036415  None
31  10  0.259314  0.115530  0.244495  0.116281  None
32  10  0.902328  0.581073  0.080335  0.583380  None
33  10  0.498177  0.630824  0.691130  0.750496  None

In [46]:
df = pd.DataFrame({'Name': ['Alice', 'Bob', 'Aritra'],
                   'Age': [25, 30, 35],
                    'Location': ['Seattle', 'New York', 'Kona']},
                   index=([10, 20, 30]))

In [47]:
df

      Name  Age  Location
10   Alice   25   Seattle
20     Bob   30  New York
30  Aritra   35      Kona

In [49]:
df.head()

      Name  Age  Location
10   Alice   25   Seattle
20     Bob   30  New York
30  Aritra   35      Kona

In [53]:
df.shape

(3, 3)

In [56]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 3 entries, 10 to 30
Data columns (total 3 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Name      3 non-null      object
 1   Age       3 non-null      int64
 2   Location  3 non-null      object
dtypes: int64(1), object(2)
memory usage: 96.0+ bytes

In [62]:
df = pd.DataFrame({

    'A': [1, 2, 3],

    'B': [4, 5, 6]

})

In [63]:
df.describe()

         A    B
count  3.0  3.0
mean   2.0  5.0
std    1.0  1.0
min    1.0  4.0
25%    1.5  4.5
50%    2.0  5.0
75%    2.5  5.5
max    3.0  6.0

In [64]:
df.mean()

A    2.0
B    5.0
dtype: float64

In [65]:
df.corr()

     A    B
A  1.0  1.0
B  1.0  1.0

In [67]:
df.max()

A    3
B    6
dtype: int64

In [68]:
df.median()

A    2.0
B    5.0
dtype: float64

In [69]:
df.std()

A    1.0
B    1.0
dtype: float64